### ISSUE TITLE
Pass TwoWire* to drivers

### ISSUE THREAD

**Issue by BourgeoisLab** [adafruit/Adafruit_SensorLab#12]
The I2C interface pointer `TwoWire *_i2c` should be passed to the drivers. This is usefull (even critical) for boards with more or different I2C interfaces.

E.g. for the LSM9DS1:
`_lsm9ds1 = new Adafruit_LSM9DS1(_i2c, 9051);`

**Comment by ladyada** [comment]
thanks, please submit a PR and we'll take a look!

**Comment by BourgeoisLab** [comment]
See PR #14
