### ISSUE TITLE
Support for LSM9DS1

### ISSUE THREAD

**Issue by hkayann** [adafruit/Adafruit_SensorLab#18]
I have Arduino Nano 33 BLE Sense which has LSM9DS1. Will you support this in the future?
I am a little bit stuck regarding how should I calibrate my IMU.

**Comment by evaherrada** [comment]
https://github.com/adafruit/adafruit_lsm9ds1 This might be what you're looking for

**Comment by hkayann** [comment]
> Designed specifically to work with the Adafruit LSM9DS1 Breakout

It seems like that is not the case as I have an Arduino Nano 33 BLE Sense.

**Comment by tyeth** [comment]
@hkayann although a lot of the Adafruit libraries mention being designed specifically for a certain breakout board, they are usually compatible with third-party products using the same sensor. If not, then pull requests are accepted so you can always add the extra functionality (like alternative address support etc).

You can try the previously linked driver repository if you're still in the same position (needing calibration). Closing this for now.
