### ISSUE TITLE
Can't compile any example

### ISSUE THREAD

**Issue by simon88** [adafruit/Adafruit_SensorLab#20]
Hi,
I'm trying to use your lib and examples but I can't campile any examples. Here is the error I got `'class Adafruit_Sensor' has no member named 'printSensorDetails'`. I have an SAMD21E17A and I got the v0.7.1

**Comment by caternuson** [comment]
Make sure all your libraries are up to date. The `printSensorDetails` method is defined here:
https://github.com/adafruit/Adafruit_Sensor/blob/69d2d4f128458c7f7e6d56b583a8261ea234971b/Adafruit_Sensor.h#L182
